application: linotify-domain
version: 1
api_version: 1
runtime: python
 
handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
- url: /static
  static_dir: static
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
- url: /cron/notice
  script: server.py
  login: admin
- url: /my/.*
  script: server.py
  login: required
- url: .*
  script: server.py
