application: linotify-domain
version: 3
api_version: 1
runtime: python

builtins:
- datastore_admin: on
- remote_api: on
- appstats: on  # See stats on /_ah/stats/
 
handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: optional
- url: /static/swf
  static_dir: static/swf
  secure: optional
  expiration: 30d
- url: /static
  static_dir: static
  secure: optional

- url: /db_update
  script: server.py
  login: admin
  secure: optional
- url: /cron/.*
  script: server.py
  login: admin
  secure: optional
- url: /my/.*
  script: server.py
  login: required
  secure: optional
- url: .*
  script: server.py
  secure: optional

