application: linotify-domain
version: 3
api_version: 1
runtime: python
 
handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: optional
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  secure: optional
- url: /static/swf
  static_dir: static/swf
  secure: optional
  expiration: 365d
- url: /static
  static_dir: static
  secure: optional

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
  secure: optional

- url: /db_update
  script: server.py
  login: admin
  secure: optional
- url: /cron/.*
  script: server.py
  login: admin
  secure: optional
- url: /my/.*
  script: server.py
  login: required
  secure: optional
- url: .*
  script: server.py
  secure: optional

